---
on:  # yamllint disable-line rule:truthy
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  pr-build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build the image
        run: docker build --no-cache --pull --tag TEST_IMAGE .

      - name: Check the image runs
        run: docker run -it TEST_IMAGE chrome --version && chromedriver --version && firefox --version && geckodriver --version
