---
name: Lint Dockerfile, build then test image
env:
  DOCKER_IMAGE: jameswilliams1/python-webdriver
  DOCKER_BUILDKIT: 1
on: push  # yamllint disable-line rule:truthy

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Dockerfile
        uses: docker://hadolint/hadolint:latest-debian
        with:
          entrypoint: hadolint
          args: --ignore DL3008 Dockerfile  # Pin versions in apt get install.

  build:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYTHON:
          - '3.7'
        DISTRO:
          - slim-buster
        BROWSER:  # all, chrome, firefox
          - all
    env:
      DOCKER_TAG: ${{ matrix.PYTHON }}-${{ matrix.DISTRO }}-${{ matrix.BROWSER }}

    steps:
      - uses: actions/checkout@v2
      - name: Build ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
        run: docker build --no-cache --pull --tag ${DOCKER_IMAGE}:${DOCKER_TAG} .
      - name: Check the image runs
        run: >-
          docker run -t --rm ${DOCKER_IMAGE}:${DOCKER_TAG}
          google-chrome --version
          && chromedriver --version
          && firefox --version
          && geckodriver --version
